name: Test Next App
on: push
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Get rep code
      uses: actions/checkout@v3
    - name: Install deps
      run: npm ci
    - name: lint app
      run: npm run lint
